### ISSUE TITLE
Environment variables should be parsed in paths in the join config

### ISSUE THREAD

**Issue by rbarghou** [jspeis/pandasplus#4]
This works: 
```yaml
global:
    source: $MY_ENV_VAR/path-to-input/
    output: $MY_ENV_VAR/path-to-output/
```

This doesn't work:
```yaml
global:
    join:
        source: $MY_ENV_VAR/path-to-join-data/
```
